### ISSUE TITLE
9: New user can create an account

### ISSUE THREAD

**Issue by MikelSage** [swdonovan/scoots_shop#16]
As a visitor 
When I visit "/" 
Then I should see a link for "Login" 
And when I click "Login" 
And I should be on the "/login" page 
And I should see a link to "Create Account" 
And when I click link "Create Account" 
And I fill in my desired credentials 
And I submit my information 
Then my current page should be "/dashboard" 
And I should see a message in the navbar that says "Logged in as SOME_USER" 
And I should see my profile information 
And I should not see a link for "Login" 
And I should see a link for "Logout"

**Comment by jimszalew** [comment]
Hey guys, I have a question about the "Create Account" button and its placement. Do you think it would be best for it to be in the navbar or just in the page?

**Comment by MikelSage** [comment]
I think it should be on the page itself in this case, on the login page an unregistered use would see.

**Comment by jimszalew** [comment]
Closed the old pull request and opened a new one with changes.
