### ISSUE TITLE
23: Admin Item Creation

### ISSUE THREAD

**Issue by MikelSage** [swdonovan/scoots_shop#44]
As an authenticated Admin: I can create an item.
As an Admin
When I visit "/admin/dashboard"
I should see a link to Create New Item
When I click that link I should be taken to admin/items/new
When I create the item it should have these attributes:
- An item must have a title, description and price.
- An item must belong to at least one category.
- The title and description cannot be empty.
- The title must be unique for all items in the system.
- The price must be a valid decimal numeric value and greater than zero.
- The photo is optional. If not present, a stand-in photo is used. (PAPERCLIP)

I should be able to click create item
Then I should be on the admin/items/:item_id

**Comment by jimszalew** [comment]
Thanks for all the help on this part gents. Please let me know if anything looks wonky.
